# w3schools (python read files)

In [15]:
f = open("24 mar.txt","r")
print(f.read())

Halo, sya sedang belajar python
di laboratorium praktikum 


# modul hal 43

In [19]:
import numpy as np
a = np. arange (15) . reshape (3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [20]:
a. shape

(3, 5)

In [21]:
a. ndim

2

In [22]:
a. dtype . name

'int32'

In [23]:
a. itemsize

4

In [24]:
a. size

15

In [25]:
type (a)

numpy.ndarray

In [26]:
b = np. array ([6 , 7, 8])
b

array([6, 7, 8])

In [27]:
type (b)

numpy.ndarray

# 5.2 membuat array

In [10]:
import numpy as np
a = np. array ([2 ,3 ,4])
a

array([2, 3, 4])

In [11]:
a. dtype

dtype('int32')

In [12]:
b = np. array ([1.2 , 3.5 , 5.1])
b

array([1.2, 3.5, 5.1])

In [13]:
b.dtype 

dtype('float64')

In [14]:
np.zeros ( (3 ,4) )


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np. ones ( (2 ,3 ,4) , dtype =np. int16 )

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [16]:
np. empty ( (2 ,3) )

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np. arange (10 ,30 ,5 )

array([10, 15, 20, 25])

In [18]:
np. arange (0 ,2 ,0.3 )

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [19]:
from numpy import pi
np. linspace (0 ,2 ,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [21]:
x = np. linspace (0 ,2*pi ,100 )

In [22]:
f = np.sin (x)

# 5.3 Menampilkan Array

In [23]:
a = np.arange (6)
print (a)

[0 1 2 3 4 5]


In [24]:
b = np. arange (12).reshape (4,3)
print (b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [25]:
c = np. arange (24).reshape (2 ,3 ,4) 
print (c)


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [26]:
print (np. arange (10000) )

[   0    1    2 ... 9997 9998 9999]


In [27]:
print (np. arange (10000) . reshape (100 ,100) )

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [28]:
print (np. arange (10000) )

[   0    1    2 ... 9997 9998 9999]
